//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcSkladowana
{
    using System;
    using System.Collections.Generic;
    
    public partial class klienci
    {
        public int k_id { get; set; }
        public string nazwa { get; set; }
        public string nip { get; set; }
    }
}
