//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcSkladowana
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KR_DEntities : DbContext
    {
        public KR_DEntities()
            : base("name=KR_DEntities")
        {
        }        
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adresy> adresies { get; set; }
        public virtual DbSet<klienci> kliencis { get; set; }
        public virtual DbSet<telefony> telefonies { get; set; }
    }
}
